### ISSUE TITLE
Bootstrap collapsed menu is not working

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/ricardovsilva.github.io#1]
When bootstrap collapse menu it simple doesn't works.
You click (or touch) in button to expand but nothing happens.

The file where menu is defined is [header.html](my-personal-blog/_includes/header.html), it's probably some mistake that I'm doing with html.

I am pretty sure that the problem is in the lines [25 - 45](https://github.com/ricardovsilva/my-personal-blog/blob/master/_includes/header.html#L25-L45)

**Comment by ricardovsilva** [comment]
Was not the responsive css missing the problem. But yes, it was some problem. Thanks to solve that :). I'm reopening this issue.

**Comment by jhonnymoreira** [comment]
The main problema in here is the lack of **2 things**:
1. **jQuery**
2. **BootstrapJS**

From [Bootstrap Navbar](http://getbootstrap.com/components/#navbar):
![Quote alerting about JavaScript and collapsed menus](https://cloud.githubusercontent.com/assets/2177742/9276485/a8a9e808-427a-11e5-8186-c51cb3007e50.png)

**Comment by ricardovsilva** [comment]
I added JQuery and BootstrapJs to header.html, 9f586fa03bf06ce6145dcf3a931f65a8cc1a8e51, and tried test, but still don't working.
Is there something I'm missing? I read the navbar docs and I could not found the point.

**Comment by jhonnymoreira** [comment]
I'll be doing the update, but since you need to read the DOM, the JS should go on footer instead of header.

**Comment by ricardovsilva** [comment]
This is something that I don't know. In real, my knowledge about DOM is very little. Do you know any good source of info?

**Comment by jhonnymoreira** [comment]
Here a good source: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model

MDN rules!

**Comment by ricardovsilva** [comment]
One problem less :) da8bb92e54390182551386a737217d2776b80d0b
