### ISSUE TITLE
Implement comments in posts

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/ricardovsilva.github.io#2]
The idea is basic. All blogs has that. Is simple allow any user to comment in posts.
Maybe I has to do some integration with social networks, I don't know yet.

**Comment by jhonnymoreira** [comment]
A good way to implement commentaries would be using the [Disqus](http://publishers.disq.us/engage) platform. Most of the sites that I visit related to _back-end_ or _front-end development_ use it as the main platform to support discussions.

**Comment by ricardovsilva** [comment]
Is Disqus free?

**Comment by ricardovsilva** [comment]
Thanks, Disqus did the trick and was easy peasy lemon squeezy. I'm closing this issue.
The commit was 8a801d2dc15be8008a9200a51660e99f53d3de23

**Comment by jhonnymoreira** [comment]
ezpz hahahaha
